import { operation, stateDir, type PackageApi } from "@stack/api";
import { z } from "zod";
import { AccessStore, scopes } from "./src/store.js";
import { startIngress, pairInput, redeemInput, refreshInput, handoffInput } from "./src/ingress.js";
import { snapshotSchema, envelope, errorEnvelope, pairResponse, redeemResponse, refreshResponse, shareRequest, shareResponse, statesResponse } from "./src/schema.js";
import { approvalInput, claimInput, enrollmentRedeemInput, inviteCreateInput, qrTextSchema, qrRenderSchema,
  previewSchema, enrollmentResponseSchema, invitationResponseSchema } from "./src/enrollment-protocol.js";
import { enrollmentOrigin, enrollmentResponse, invitationResponse } from "./src/enrollment.js";
import { renderQr } from "./src/qr.js";

type Context = { store: AccessStore; ingress: Awaited<ReturnType<typeof startIngress>>; env: NodeJS.ProcessEnv };
export const api: PackageApi<Context, "access_changed"> = {
  operations: [
    operation({ name: "enrollment_invite_create", description: "Create a one-use QR invitation on trusted local control with explicit kind and scopes. Persist a random 32-byte base64url secret, UUID and absolute expiry before calling; exact retries recover until expiry (at most ten minutes). The QR contains invitation authority: show only to the intended device, never log it. Only local control may seed access:enroll. Requires configured Access HTTPS origin.",
      input: inviteCreateInput, output: invitationResponseSchema,
      async call(ctx, input) { return invitationResponse(ctx.store.createInvitation(input, enrollmentOrigin(ctx.env)), ctx.store.now()); } }),
    operation({ name: "enrollment_invite_revoke", description: "Revoke a QR invitation and its unredeemed enrollment. Already issued device credentials remain independent; revoke those separately.",
      input: z.strictObject({ id: z.uuid() }), output: z.object({ revoked: z.boolean() }), async call(ctx, input) { return ctx.store.revokeInvitation(input.id); } }),
    operation({ name: "enrollment_inspect", description: "Validate a new device's offline request QR and preview its claimed label, kind, requested permissions and request fingerprint. Does not approve or issue credentials. Labels are claims; compare the request fingerprint on the device.",
      input: z.strictObject({ request: qrTextSchema }), output: previewSchema, annotations: { readOnlyHint: true }, async call(ctx, input) { return ctx.store.previewEnrollment(input.request); } }),
    operation({ name: "enrollment_approve", description: "Explicitly approve a scanned device request on trusted local control. Selected scopes must be requested. Returns a credential-free connection receipt QR for the device to import by scan or paste; only its retained secret and private signing key can redeem. Exact retries recover. Never approve a request merely because a QR was scanned.",
      input: approvalInput, output: enrollmentResponseSchema, async call(ctx, input) { return enrollmentResponse(ctx.store.approveEnrollment(input.request, input.scopes, enrollmentOrigin(ctx.env)), ctx.store.now()); } }),
    operation({ name: "enrollment_cancel", description: "Cancel an unredeemed enrollment. Cancellation cannot revoke an already issued credential; use access_revoke for that.",
      input: z.strictObject({ id: z.uuid() }), output: z.object({ cancelled: z.boolean() }), async call(ctx, input) { return ctx.store.cancelEnrollment(input.id); } }),
    operation({ name: "enrollment_qr_render", description: "Validate and render a version-1 Stack enrollment request, invitation or receipt as a QR module matrix. No network access. Render black modules on white with the returned four-module quiet zone; show destination and expiry alongside it. Invitation text is sensitive.",
      input: z.strictObject({ text: qrTextSchema }), output: qrRenderSchema, annotations: { readOnlyHint: true }, async call(ctx, input) { return renderQr(input.text, ctx.store.now()); } }),
    operation({ name: "access_snapshot", description: "Read clients, pending approval codes, QR invitation/enrollment metadata, grants with durable enrollment provenance, credential and remote UI session metadata, and the last 100 audit entries. Never returns secrets or invitation QR payloads. Public-cloud grants are foundations only; no public listener or connector tokens are issued.", input: z.strictObject({}),
      output: snapshotSchema, annotations: { readOnlyHint: true },
      async call(ctx) { return snapshotSchema.parse({ ...ctx.store.inventory(), ingress: ctx.ingress ? { host: ctx.ingress.host, port: ctx.ingress.port, artifactPort: ctx.ingress.artifactPort, uiPort: ctx.ingress.uiPort } : null }); } }),
    operation({ name: "pairing_decide", description: "Approve a selected subset of requested scopes or deny a pairing after comparing the full human code. Omitted scopes approve the requested set. Only trusted local control can decide; expiry and transition are atomic.", input: z.strictObject({ id: z.uuid(), code: z.string(), approve: z.boolean(), scopes: z.array(z.enum(scopes)).max(scopes.length).optional() }), output: z.object({ state: z.string() }),
      async call(ctx, input) { return ctx.store.approve(input.id, input.code, input.approve, input.scopes); } }),
    operation({ name: "grant_update", description: "Extend or restrict an active grant without re-pairing. Requires the observed revision. New scopes apply immediately to tokens and Content sessions; cloud grants accept explicit package.operation selections only.", input: z.strictObject({ id: z.uuid(), expectedRevision: z.number().int().positive(), scopes: z.array(z.enum(scopes)).max(scopes.length), operations: z.array(z.string().regex(/^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$/)).max(100) }), output: z.object({ id: z.uuid(), revision: z.number().int() }),
      async call(ctx, input) { return ctx.store.updateGrant(input.id, input.expectedRevision, input.scopes, input.operations); } }),
    operation({ name: "grant_evaluate_operation", description: "Evaluate an authenticated cloud grant against its exact network policy and package.operation selection. Local authorization foundation only; this issues no credential, invokes no operation and creates no Bot/Worker MCP identity.", input: z.strictObject({ grantId: z.uuid(), network: z.enum(["tailnet", "public-cloud"]), operation: z.string().regex(/^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$/) }), output: z.object({ allowed: z.boolean(), grantId: z.uuid(), operation: z.string() }), annotations: { readOnlyHint: true },
      async call(ctx, input) { return ctx.store.evaluateOperation(input.grantId, input.network, input.operation); } }),
    operation({ name: "access_revoke", description: "Immediately revoke one client, grant or individual credential, including all its access tokens, remote UI connections and content sessions. History and admission receipts are retained.", input: z.strictObject({ kind: z.enum(["client", "grant", "credential"]), id: z.uuid() }), output: z.object({ revoked: z.boolean() }),
      async call(ctx, input) { return ctx.store.revoke(input.kind, input.id); } }),
    operation({ name: "cloud_grant_create", description: "Record a public-cloud grant with an explicit positive list of package.operation names. This foundation issues no credentials and exposes no remote MCP; device credentials can never use this network policy.", input: z.strictObject({ label: z.string().trim().min(1).max(100), operations: z.array(z.string().regex(/^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$/)).min(1).max(100) }), output: z.object({ id: z.uuid(), clientId: z.uuid(), network: z.string(), operations: z.array(z.string()), credentialIssued: z.boolean() }),
      async call(ctx, input) { return ctx.store.cloudGrant(input.label, [...new Set(input.operations)]); } }),
  ],
  http: [{ name: "private", kind: "json", authentication: "bearer", description: "Direct TLS tailnet ingress; socket peer and local tailscaled are checked on EVERY request, including pairing and preflight. Pairing uses a separate redemption secret, not the displayed code.", routes: [
    { method: "GET", path: "/v1/access/identity", format: "application/json", description: "Read the stable server identity before sending credentials. Requires verified tailnet provenance, but no bearer. HTTPS authenticates the server; this ID fences accidental replacement and destination changes.", response: envelope(z.object({ serverId: z.uuid() })), error: errorEnvelope },
    { method: "GET", path: "/v1/access/me", format: "application/json", description: "Verify a Brain audience credential and read its current grant scopes; no data scope is needed. Requires X-Stack-Server-ID, as do redemption and all authenticated JSON requests.", response: envelope(z.object({ serverId: z.uuid(), clientId: z.uuid(), credentialId: z.uuid(), scopes: z.array(z.enum(scopes)) })), error: errorEnvelope },
    { method: "POST", path: "/v1/access/pair", format: "application/json", description: "Begin a retry-safe expiring pairing; persist a random 32-byte base64url redemption secret before sending. No bearer required.", request: pairInput, response: pairResponse, error: errorEnvelope },
    { method: "POST", path: "/v1/access/redeem", format: "application/json", description: "Redeem an approved pairing or recover the identical receipt before expiry. Authenticates with redemption secret.", request: redeemInput, response: redeemResponse, error: errorEnvelope },
    { method: "POST", path: "/v1/access/refresh", format: "application/json", description: "Rotate refresh credential and issue a five-minute audience token. Persist request ID before sending; exact retries recover for five minutes.", request: refreshInput, response: refreshResponse, error: errorEnvelope },
    { method: "POST", path: "/v1/access/enrollment/claim", format: "application/json", description: "Claim a local invitation for one offline device request using the invitation secret. Atomic one-use claim; exact retries return the same connection receipt. Requires tailnet, configured Host and pinned server ID. No bearer required.", request: claimInput, response: envelope(enrollmentResponseSchema), error: errorEnvelope },
    { method: "POST", path: "/v1/access/enrollment/inspect", format: "application/json", description: "Preview a scanned request and scopes this sponsor may grant. Requires access-audience bearer, access:enroll and a non-browser client. No approval occurs.", request: z.strictObject({ request: qrTextSchema }), response: envelope(previewSchema), error: errorEnvelope },
    { method: "POST", path: "/v1/access/enrollment/approve", format: "application/json", description: "Explicitly induct a new device using access-audience bearer and access:enroll. Scopes must be requested and held by the sponsor; access:enroll cannot be delegated. Returns a credential-free receipt QR/paste handoff. Sponsor authority is rechecked at redemption. All requests remain direct-tailnet only.", request: approvalInput, response: envelope(enrollmentResponseSchema), error: errorEnvelope },
    { method: "POST", path: "/v1/access/enrollment/cancel", format: "application/json", description: "Cancel only this sponsor credential's own unredeemed enrollment. Requires access-audience bearer and access:enroll. Does not revoke independent issued credentials.", request: z.strictObject({ id: z.uuid() }), response: envelope(z.object({ cancelled: z.boolean() })), error: errorEnvelope },
    { method: "POST", path: "/v1/access/enrollment/redeem", format: "application/json", description: "Redeem with the target's 256-bit secret and Ed25519 proof bound to the server origin, identity and enrollment. A substituted return receipt cannot produce proof for this destination. Exact retries recover until expiry or first refresh. Requires tailnet, configured Host and pinned server ID; no bearer.", request: enrollmentRedeemInput, response: redeemResponse, error: errorEnvelope },
    { method: "POST", path: "/v1/content/handoff", format: "application/json", description: "Mint a one-use 60-second resource-scoped browser handoff; browser opens /session#handoff on the selected origin.", request: handoffInput, response: envelope(z.object({ handoff: z.string(), expiresAt: z.number() })), error: errorEnvelope },
    { method: "POST", path: "/v1/access/disconnect", format: "application/json", description: "Revoke this device credential.", response: envelope(z.object({ revoked: z.boolean() })), error: errorEnvelope },
    { method: "POST", path: "/v1/share", format: "application/json", description: "Admit a Brain share and record this client's receipt, including duplicates.", request: shareRequest, response: shareResponse, error: errorEnvelope },
    { method: "GET", path: "/v1/shares", format: "application/json", description: "Read only jobs this client has admitted; requires brain:status.", query: z.object({ job_ids: z.string().optional() }), response: statesResponse, error: errorEnvelope },
    { method: "GET", path: "/v1/health", format: "application/json", description: "Authenticated Brain audience health.", response: envelope(z.object({ version: z.literal(1), ok: z.literal(true) })), error: errorEnvelope },
  ] }, { name: "content", kind: "static", authentication: "bearer", description: "Authenticated documents and separate sandboxed artifact origin. Document cookies and artifact view credentials are short-lived and resource-scoped; every request requires tailnet provenance.", routes: [
    { method: "GET", path: "/d/*", format: "text/html", description: "Rendered document on document origin." },
    { method: "GET", path: "/a/*", format: "application/octet-stream", description: "Artifact on the separate artifact origin; scripts have opaque origin and no network access." },
    { method: "GET", path: "/c/*", format: "application/octet-stream", description: "Content item on artifact origin." },
    { method: "GET", path: "/view/*", format: "application/octet-stream", description: "Artifact view credential followed by its resource path. Covers one item or immutable bundle for fifteen minutes; still requires tailnet. Relative bundle assets use the same scoped path." },
    { method: "GET", path: "/session", format: "text/html", description: "Exchange a fragment-carried one-use handoff for a resource-scoped document cookie or artifact view path." },
    { method: "POST", path: "/session", format: "application/json", description: "Consume a handoff on its exact origin." },
  ] }, { name: "ui", kind: "static", authentication: "bearer", description: "Separate direct-tailnet TLS origin for paired browser sessions. No Access control operations or internal MCP forwarding; unsafe requests require the exact UI Origin.", routes: [
    { method: "GET", path: "/connect", format: "text/html", description: "Plain-browser pairing page; persists a redemption secret before admission. Approval stays on trusted local control." },
    { method: "GET", path: "/connect/identity", format: "application/json", description: "Read this installation's stable server identity without a session." },
    { method: "POST", path: "/connect/pair", format: "application/json", description: "Request browser-kind pairing with a client-generated persistent redemption secret.", request: pairInput, response: envelope(z.object({ id: z.uuid(), code: z.string(), expiresAt: z.number(), serverId: z.uuid() })), error: errorEnvelope },
    { method: "POST", path: "/connect/redeem", format: "application/json", description: "Redeem an approved browser pairing using the separate secret.", request: redeemInput, response: redeemResponse, error: errorEnvelope },
    { method: "POST", path: "/connect/session", format: "application/json", description: "Rotate a browser credential into Secure HttpOnly UI and refresh cookies; requires ui:view.", request: z.strictObject({ refreshToken: z.string(), requestId: z.uuid() }), response: envelope(z.object({ scopes: z.array(z.enum(scopes)), expiresAt: z.number() })), error: errorEnvelope },
    { method: "POST", path: "/connect/refresh", format: "application/json", description: "Rotate the short-lived UI session and refresh cookie; uses only the HttpOnly refresh cookie.", response: envelope(z.object({ scopes: z.array(z.enum(scopes)), expiresAt: z.number() })), error: errorEnvelope },
    { method: "GET", path: "/connect/me", format: "application/json", description: "Read this viewer's live scopes and separate Content origins.", response: envelope(z.object({ scopes: z.array(z.enum(scopes)), documentOrigin: z.string(), artifactOrigin: z.string() })), error: errorEnvelope },
    { method: "POST", path: "/v1/content/handoff", format: "application/json", description: "Mint one resource-scoped Content handoff as this browser principal; requires ui:view and content:read.", request: handoffInput, response: envelope(z.object({ handoff: z.string(), expiresAt: z.number() })), error: errorEnvelope },
    { method: "GET", path: "/", format: "text/html", description: "Authenticated Fleet bench proxied from the loopback Next server, without trusted-local SSR reads." },
    { method: "GET", path: "/{space}", format: "text/html", description: "Authenticated named UI space proxied from the loopback Next server, without trusted-local SSR reads." },
    { method: "GET", path: "/_next/*", format: "application/octet-stream", description: "Authenticated UI assets. No shared/public asset origin." },
    { method: "GET", path: "/websocket", format: "application/websocket", description: "Authenticated WebSocket upgrade with scoped operations and topics; live revocation closes connections." },
  ] }],
  events: { topics: { access_changed: "Access pairing, invitation, enrollment, client, grant or credential state changed; re-read access_snapshot." }, start(ctx, publish) { ctx.store.changed = () => publish("access_changed"); return () => { ctx.store.changed = undefined; }; } },
  async createContext(env) { const store = new AccessStore(stateDir(env)); try { return { store, ingress: await startIngress(store, env), env }; } catch (error) { store.close(); throw error; } },
  async closeContext(ctx) { await ctx.ingress?.close(); ctx.store.close(); },
};
