import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { AccessStore } from "../src/store.js";
import { api } from "../api.js";
import { createEnrollmentIntent } from "../src/enrollment-client.js";
import { encodeQr } from "../src/enrollment-protocol.js";
import type { StatePlan } from "@stack/api";

const apply = (plan: StatePlan) => ({ planId: plan.id, expectedRevision: plan.revision, requestId: randomUUID() });
test("exact expired Access retirement preserves identities, revocations, enrollment evidence and audit, with durable nonreplaying receipts", async () => {
  const root = await mkdtemp(join(tmpdir(), "access-history-")); let now = Date.now(), store = new AccessStore(root, () => now);
  const call = async (name: string, input: unknown, invocation?: any) => { const op = api.operations.find(op => op.name === name)!; return op.output.parse(await op.call({ store, ingress: null, env: {} }, op.input.parse(input), invocation)) as any; };
  const secret = () => randomBytes(32).toString("base64url");
  try {
    const input = { requestId: randomUUID(), label: "Browser", kind: "browser", scopes: ["ui:view" as const], redemptionSecret: secret() };
    const paired = store.pair(input); store.approve(paired.id, paired.code, true); const credential = store.redeem(paired.id, input.redemptionSecret);
    const session = store.startUi(credential.refreshToken, randomUUID()), sessionId = String(store.inventory().uiSessions[0]!.id);
    const siblingInput = { ...input, requestId: randomUUID(), label: "Sibling", redemptionSecret: secret() }, sibling = store.pair(siblingInput);
    const inviteInput = { requestId: randomUUID(), secret: secret(), kind: "android", scopes: ["brain:share" as const], expiresAt: now + 60_000 };
    const invite = store.createInvitation(inviteInput, "https://stack.example");
    const intent = await createEnrollmentIntent({ kind: "android", label: "Phone", scopes: ["brain:share"] }, now);
    const enrollment = store.claimInvitation(invite.id, invite.secret, encodeQr(intent.request));
    const active = await call("access_history_plan", { kind: "ui_sessions", ids: [sessionId] }); assert.ok(active.blockedBy.length);
    await assert.rejects(call("access_history_clear", apply(active)), /authority changed/);
    store.revoke("credential", credential.credentialId);
    const identity = store.serverId, before = store.inventory();
    now += 300_001;
    const uiPlan = await call("access_history_plan", { kind: "ui_sessions", ids: [sessionId] }), uiRequest = apply(uiPlan);
    const uiReceipt = await call("access_history_clear", uiRequest); assert.equal(uiReceipt.status, "completed");
    assert.deepEqual(await call("access_history_clear", uiRequest), uiReceipt);
    assert.ok(!store.inventory().uiSessions.some(row => row.id === sessionId));
    assert.throws(() => store.ui(session.accessToken));
    assert.deepEqual(store.inventory().credentials, before.credentials); assert.deepEqual(store.inventory().grants, before.grants); assert.deepEqual(store.inventory().clients, before.clients);
    const stale = await call("access_history_plan", { kind: "expired_invitations", ids: [invite.id] });
    store.db.prepare("UPDATE invitations SET revoked=? WHERE id=?").run(now, invite.id);
    await assert.rejects(call("access_history_clear", apply(stale)), /changed/);
    const invitePlan = await call("access_history_plan", { kind: "expired_invitations", ids: [invite.id] });
    await call("access_history_clear", apply(invitePlan));
    assert.ok(store.inventory().enrollments.some((row: any) => row.id === enrollment.id), "device QR replay authority outlives expired invitation");
    assert.ok(store.inventory().pairings.some(row => row.id === sibling.id), "exact manual retirement does not run broad expiry cleanup");
    assert.ok(before.audit.every(row => store.inventory().audit.some(after => after.seq === row.seq)), "manual retirement does not prune audit");
    now += 300_001;
    const pairPlan = await call("access_history_plan", { kind: "expired_pairings", ids: [paired.id] }), pairRequest = apply(pairPlan);
    const pairReceipt = await call("access_history_clear", pairRequest); assert.equal(pairReceipt.status, "completed");
    const pending = await call("access_history_plan", { kind: "expired_pairings", ids: [sibling.id] }), pendingInput = apply(pending);
    store.maintenance.begin(pendingInput, pending); store.close(); store = new AccessStore(root, () => now);
    assert.equal(store.serverId, identity); assert.equal((await call("access_history_clear", pendingInput)).status, "unknown");
    assert.ok(store.inventory().pairings.some(row => row.id === sibling.id));
    assert.deepEqual(await call("access_history_clear", pairRequest), pairReceipt);
    assert.deepEqual((await call("access_state_receipt_get", { requestId: uiRequest.requestId })).receipt, uiReceipt);
    assert.throws(() => store.pair(input), /pairing_retired/);
    assert.throws(() => store.createInvitation({ ...inviteInput, expiresAt: now + 60_000 }, "https://stack.example"), /invitation_retired/);
    assert.throws(() => store.refresh(session.refreshToken, randomUUID(), "ui"), /credential_revoked/);
    await assert.rejects(call("access_history_plan", { kind: "audit_before", before: now }), /Invalid|Unrecognized/);
    await assert.rejects(call("access_history_plan", { kind: "expired_pairings", ids: [sibling.id] }, { transport: "mcp", botId: null, instance: null, threadId: null, sessionId: null }), /operator authority/);
  } finally { store.close(); await rm(root, { recursive: true, force: true }); }
});
