import { stateCategories } from "@stack/api";
export const workerStateCategories = stateCategories("worker", [
  { id: "settings-receipts", kind: "history", paths: [], ownership: "shared", reads: ["worker_settings_read"], actions: ["worker_settings_receipts_plan"], retention: "Retire exact targets' receipts older than current revision and >=7 days; unknown-age legacy receipts and permanent digest/revision tombstones remain. Saved/loaded settings unchanged.", regeneration: "Explicit settings edits create new receipts; no implicit turn or runtime." },
  { id: "ledger", kind: "history", paths: ["workers.sqlite", "workers.sqlite-wal"], reads: ["worker_list", "worker_detail", "worker_turn_list", "worker_record_list", "worker_work_list"], actions: ["worker_close", "worker_remove", "worker_state_plan"],
    retention: "Closed-Worker transcript redaction retains turn IDs, replay digests, outcomes, usage, settings and captured Work context. Removal clears Stack records but not native copies.", regeneration: "Explicit Worker admissions; unknown turns must not be dispatched again." },
  { id: "worktrees", kind: "workspace", paths: ["workers/worktrees", "workers/roles"], reads: ["worker_list", "worker_diff", "worker_workspace_list", "worker_workspace_read", "worker_state_branches"], actions: ["worker_remove", "worker_state_plan"],
    retention: "Closed-only exact owned Git reset retains old tip at refs/stack/retained/<worker> and frozen Role files. Only recorded unreferenced, unchecked-out branches can be collected; unmerged requires an exact override. Source checkout/remotes remain.", regeneration: "New Worker creation creates a new worktree and frozen Role snapshot." },
  { id: "native-sessions", kind: "conversation", paths: [], ownership: "shared", reads: ["worker_detail", "worker_runtime_list"], actions: ["worker_state_plan"],
    retention: "Exact closed native-session purge requires disabled account, idle sign-in and drained runtime, scope-verified provider version and sibling/credential checks. Whole profiles, native logs/caches, shares, Stack copies and backups remain.", regeneration: "New explicit Workers create new native sessions; closed/unknown maintenance never resumes a session.", issues: ["Native bytes are not measured by the Worker ledger inventory. Unsupported versions, missing/unsafe/ambiguous scope and untracked external writers block cleanup."] },
  { id: "catalogs", kind: "cache", paths: [], ownership: "shared", authority: "derived", reads: ["worker_catalog"], actions: ["worker_state_plan"], retention: "Account-shared Stack catalog.json and in-memory cache only. Sessions, credentials and settings remain; in-flight discovery blocks clearing.", regeneration: "Explicit later native discovery recreates the derived catalog; cleanup admits no turn." },
]);
